/**
 * Complete Ant Design default tokens (non-color)
 * Based on Ant Design v5/v6 default theme
 */
export declare const DEFAULT_TOKENS: {
    readonly fontSize: 14;
    readonly fontSizeSM: 12;
    readonly fontSizeLG: 16;
    readonly fontSizeXL: 20;
    readonly fontSizeHeading1: 38;
    readonly fontSizeHeading2: 30;
    readonly fontSizeHeading3: 24;
    readonly fontSizeHeading4: 20;
    readonly fontSizeHeading5: 16;
    readonly fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'";
    readonly fontFamilyCode: "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace";
    readonly lineHeight: 1.5715;
    readonly lineHeightSM: 1.66;
    readonly lineHeightLG: 1.5;
    readonly lineHeightHeading1: 1.21;
    readonly lineHeightHeading2: 1.35;
    readonly lineHeightHeading3: 1.35;
    readonly lineHeightHeading4: 1.4;
    readonly lineHeightHeading5: 1.5;
    readonly fontWeightStrong: 600;
    readonly sizeStep: 4;
    readonly sizeUnit: 4;
    readonly borderRadius: 6;
    readonly borderRadiusXS: 2;
    readonly borderRadiusSM: 4;
    readonly borderRadiusLG: 8;
    readonly borderRadiusOuter: 4;
    readonly lineWidth: 1;
    readonly lineWidthBold: 2;
    readonly lineWidthFocus: 4;
    readonly controlHeight: 32;
    readonly controlHeightSM: 24;
    readonly controlHeightLG: 40;
    readonly controlHeightXS: 16;
    readonly padding: 16;
    readonly paddingXS: 8;
    readonly paddingSM: 12;
    readonly paddingLG: 24;
    readonly paddingXL: 32;
    readonly paddingContentHorizontal: 16;
    readonly paddingContentVertical: 12;
    readonly margin: 16;
    readonly marginXS: 8;
    readonly marginSM: 12;
    readonly marginLG: 24;
    readonly marginXL: 32;
    readonly marginXXL: 48;
    readonly motionUnit: 0.1;
    readonly motionBase: 0;
    readonly motionEaseInOut: "cubic-bezier(0.645, 0.045, 0.355, 1)";
    readonly motionEaseOut: "cubic-bezier(0.215, 0.61, 0.355, 1)";
    readonly motionEaseIn: "cubic-bezier(0.55, 0.055, 0.675, 0.19)";
    readonly motionEaseOutBack: "cubic-bezier(0.12, 0.4, 0.29, 1.46)";
    readonly motionEaseInBack: "cubic-bezier(0.71, -0.46, 0.88, 0.6)";
    readonly motionEaseOutCirc: "cubic-bezier(0.08, 0.82, 0.17, 1)";
    readonly motionEaseInCirc: "cubic-bezier(0.6, 0.04, 0.98, 0.34)";
    readonly motionEaseInOutCirc: "cubic-bezier(0.78, 0.14, 0.15, 0.86)";
    readonly motionDurationFast: "0.1s";
    readonly motionDurationMid: "0.2s";
    readonly motionDurationSlow: "0.3s";
    readonly zIndexBase: 0;
    readonly zIndexPopupBase: 1000;
    readonly opacityLoading: 0.65;
    readonly opacityImage: 1;
    readonly boxShadow: "\n    0 6px 16px 0 rgba(0, 0, 0, 0.08),\n    0 3px 6px -4px rgba(0, 0, 0, 0.12),\n    0 9px 28px 8px rgba(0, 0, 0, 0.05)\n  ";
    readonly boxShadowSecondary: "\n    0 6px 16px 0 rgba(0, 0, 0, 0.08),\n    0 3px 6px -4px rgba(0, 0, 0, 0.12),\n    0 9px 28px 8px rgba(0, 0, 0, 0.05)\n  ";
    readonly boxShadowTertiary: "\n    0 1px 2px 0 rgba(0, 0, 0, 0.03),\n    0 1px 6px -1px rgba(0, 0, 0, 0.02),\n    0 2px 4px 0 rgba(0, 0, 0, 0.02)\n  ";
    readonly wireframe: false;
    readonly screenXS: 480;
    readonly screenXSMin: 480;
    readonly screenSM: 576;
    readonly screenSMMin: 576;
    readonly screenMD: 768;
    readonly screenMDMin: 768;
    readonly screenLG: 992;
    readonly screenLGMin: 992;
    readonly screenXL: 1200;
    readonly screenXLMin: 1200;
    readonly screenXXL: 1600;
    readonly screenXXLMin: 1600;
};
export type TokenKeys = keyof typeof DEFAULT_TOKENS;
//# sourceMappingURL=tokens.d.ts.map